# Desafío - Tipos y estructuras de Datos (Parte II)

In [1]:
import pandas as pd #importamos pandas para poder utilizar sus funciones dentro de nuestro trabajo

In [2]:
astro = pd.read_csv("resumen_resultados_astronautas.csv", sep= ",", encoding = "UTF-8") #le damos nombre a nuestro df y lo relacionamos con lo que está dentro del archivo abierto

In [3]:
astro.head() #hacemos este paso para evidenciar que se cargo bien el documento y así también conocer sus columnas

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica
0,Alana Morillo,32,75,180,93,88,78,89,6,Si
1,Fátima Tafalla,27,68,167,82,95,81,87,4,Si
2,Sofía Puig,29,80,185,85,80,90,91,3,Si
3,Valentina Tasis,30,65,175,90,91,85,92,2,No
4,Regina Cicerón,31,76,183,89,87,83,90,7,Si

In [4]:
astro.dtypes #Ejecuto este comando para conocer en que datos está cada columna, así saber si necesito convertir alguna cuando quiera ejecutar alguna operatoria o así.

nombre                    object
edad                       int64
peso                       int64
altura                     int64
evaluacion_fisica          int64
evaluacion_psicologica     int64
evaluacion_adaptativa      int64
evaluacion_medica          int64
anos_experiencia           int64
califica                  object
dtype: object

In [21]:
astro["altura"]= astro["altura"]/100 #Convertimos el valor en metros dividiendo por 100.
astro.head()

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC
0,Alana Morillo,32,75,1.80,93,88,78,89,6,Si,23.148148
1,Fátima Tafalla,27,68,1.67,82,95,81,87,4,Si,24.382373
2,Sofía Puig,29,80,1.85,85,80,90,91,3,Si,23.374726
3,Valentina Tasis,30,65,1.75,90,91,85,92,2,No,21.224490
4,Regina Cicerón,31,76,1.83,89,87,83,90,7,Si,22.694019

In [24]:
astro["IMC"] = (astro["peso"]/(astro["altura"]*astro["altura"])).round(1) #Utilizamos la fórmula IMC=m/h*h e incluimos la columna IMC

In [36]:
astro.head()

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones
0,Alana Morillo,32,75,1.80,93,88,78,89,6,Si,23.1,87.00
1,Fátima Tafalla,27,68,1.67,82,95,81,87,4,Si,24.4,86.25
2,Sofía Puig,29,80,1.85,85,80,90,91,3,Si,23.4,86.50
3,Valentina Tasis,30,65,1.75,90,91,85,92,2,No,21.2,89.50
4,Regina Cicerón,31,76,1.83,89,87,83,90,7,Si,22.7,87.25

In [30]:
astro["promedio_evaluaciones"] = (astro["evaluacion_fisica"]+astro["evaluacion_psicologica"]+astro["evaluacion_adaptativa"]+astro["evaluacion_medica"])/4
#Creamos la columna de promedio evaluaciones

In [41]:
astro2 = astro[(astro["IMC"]>=18.5) & (astro["IMC"]<= 24.9)] #Se filtra solo los astronautas que cumplen con la condición solicitada de los límites de IMC
astro2

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones
0,Alana Morillo,32,75,1.80,93,88,78,89,6,Si,23.1,87.00
1,Fátima Tafalla,27,68,1.67,82,95,81,87,4,Si,24.4,86.25
2,Sofía Puig,29,80,1.85,85,80,90,91,3,Si,23.4,86.50
3,Valentina Tasis,30,65,1.75,90,91,85,92,2,No,21.2,89.50
4,Regina Cicerón,31,76,1.83,89,87,83,90,7,Si,22.7,87.25
5,Amaya de la Cruz,26,64,1.70,80,94,79,86,4,No,22.1,84.75
6,María Juderías,28,78,1.82,88,85,87,92,5,Si,23.5,88.00
8,Consuela Arboleda,33,77,1.88,94,83,89,93,8,Si,21.8,89.75
9,María José Franco,29,70,1.75,87,90,80,89,2,No,22.9,86.50
10,Emanuel Gálvez,27,73,1.81,84,89,84,87,3,Si,22.3,86.00
11,Alberto Graciani,28,62,1.63,81,93,77,85,5,No,23.3,84.00
12,Patricio Encarnación,30,81,1.90,93,86,88,91,4,Si,22.4,89.50
13,Cristóbal Miralles,31,72,1.74,88,91,86,92,6,No,23.8,89.25
14,Pablo Cotilla,27,75,1.78,86,87,85,89,2,Si,23.7,86.75
15,Pablo Capmany,29,69,1.71,82,94,80,88,4,No,23.6,86.00
16,Nicolás Cambeiro,29,68,1.75,88,90,81,90,2,No,22.2,87.25
17,Daniel Sánchez,26,63,1.67,80,93,78,85,4,No,22.6,84.00
18,Samuel Gálvez,22,74,1.83,91,91,91,86,3,Si,22.1,89.75
20,Kevin Pareja,27,61,1.77,85,90,87,79,2,Si,19.5,85.25
21,Estefania Manzanares,31,79,1.79,89,82,85,81,5,Si,24.7,84.25
23,Christopher Berganza,23,70,1.73,92,93,92,85,1,Si,23.4,90.50
24,Álvaro Espina,30,76,1.80,90,84,87,82,4,Si,23.5,85.75
25,Leonardo Magrina,39,65,1.71,79,92,90,85,8,No,22.2,86.50
27,Sophie González,36,75,1.76,85,82,84,80,7,No,24.2,82.75
28,Alexia Gaos,21,69,1.69,93,94,93,86,0,Si,24.2,91.50
29,Fátima Varela,33,73,1.82,91,90,91,88,5,Si,22.0,90.00
30,Clara Arias,44,63,1.62,77,87,88,84,11,No,24.0,84.00
31,Paloma Berganza,28,62,1.74,87,85,87,78,3,Si,20.5,84.25

In [43]:
astro2= astro[(astro["IMC"]>=18.5) & (astro["IMC"]<= 24.9) & (astro["promedio_evaluaciones"]>= 87)]
#El promedio de las 4 evaluaciones debe ser mayor o igual a 87. Filtra el DataFrame resultante y agrega esta condición al filtro 
#aplicado en el paso anterior.

astro2

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones
0,Alana Morillo,32,75,1.80,93,88,78,89,6,Si,23.1,87.00
3,Valentina Tasis,30,65,1.75,90,91,85,92,2,No,21.2,89.50
4,Regina Cicerón,31,76,1.83,89,87,83,90,7,Si,22.7,87.25
6,María Juderías,28,78,1.82,88,85,87,92,5,Si,23.5,88.00
8,Consuela Arboleda,33,77,1.88,94,83,89,93,8,Si,21.8,89.75
12,Patricio Encarnación,30,81,1.90,93,86,88,91,4,Si,22.4,89.50
13,Cristóbal Miralles,31,72,1.74,88,91,86,92,6,No,23.8,89.25
16,Nicolás Cambeiro,29,68,1.75,88,90,81,90,2,No,22.2,87.25
18,Samuel Gálvez,22,74,1.83,91,91,91,86,3,Si,22.1,89.75
23,Christopher Berganza,23,70,1.73,92,93,92,85,1,Si,23.4,90.50
28,Alexia Gaos,21,69,1.69,93,94,93,86,0,Si,24.2,91.50
29,Fátima Varela,33,73,1.82,91,90,91,88,5,Si,22.0,90.00

In [45]:
astro2= astro[(astro["IMC"]>=18.5) & (astro["IMC"]<= 24.9) & (astro["promedio_evaluaciones"]>= 87)].reset_index()
#Reinicia el índice del DataFrame resultante.
astro2

,index,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones
0,0,Alana Morillo,32,75,1.80,93,88,78,89,6,Si,23.1,87.00
1,3,Valentina Tasis,30,65,1.75,90,91,85,92,2,No,21.2,89.50
2,4,Regina Cicerón,31,76,1.83,89,87,83,90,7,Si,22.7,87.25
3,6,María Juderías,28,78,1.82,88,85,87,92,5,Si,23.5,88.00
4,8,Consuela Arboleda,33,77,1.88,94,83,89,93,8,Si,21.8,89.75
5,12,Patricio Encarnación,30,81,1.90,93,86,88,91,4,Si,22.4,89.50
6,13,Cristóbal Miralles,31,72,1.74,88,91,86,92,6,No,23.8,89.25
7,16,Nicolás Cambeiro,29,68,1.75,88,90,81,90,2,No,22.2,87.25
8,18,Samuel Gálvez,22,74,1.83,91,91,91,86,3,Si,22.1,89.75
9,23,Christopher Berganza,23,70,1.73,92,93,92,85,1,Si,23.4,90.50
10,28,Alexia Gaos,21,69,1.69,93,94,93,86,0,Si,24.2,91.50
11,29,Fátima Varela,33,73,1.82,91,90,91,88,5,Si,22.0,90.00

In [46]:
#Modifica el valor de la columna "califica", para que diga "Si" en todas las filas del DataFrame resultante.
astro2["califica"] = astro2["califica"].replace("No","Si") #
astro2

,index,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones
0,0,Alana Morillo,32,75,1.80,93,88,78,89,6,Si,23.1,87.00
1,3,Valentina Tasis,30,65,1.75,90,91,85,92,2,Si,21.2,89.50
2,4,Regina Cicerón,31,76,1.83,89,87,83,90,7,Si,22.7,87.25
3,6,María Juderías,28,78,1.82,88,85,87,92,5,Si,23.5,88.00
4,8,Consuela Arboleda,33,77,1.88,94,83,89,93,8,Si,21.8,89.75
5,12,Patricio Encarnación,30,81,1.90,93,86,88,91,4,Si,22.4,89.50
6,13,Cristóbal Miralles,31,72,1.74,88,91,86,92,6,Si,23.8,89.25
7,16,Nicolás Cambeiro,29,68,1.75,88,90,81,90,2,Si,22.2,87.25
8,18,Samuel Gálvez,22,74,1.83,91,91,91,86,3,Si,22.1,89.75
9,23,Christopher Berganza,23,70,1.73,92,93,92,85,1,Si,23.4,90.50
10,28,Alexia Gaos,21,69,1.69,93,94,93,86,0,Si,24.2,91.50
11,29,Fátima Varela,33,73,1.82,91,90,91,88,5,Si,22.0,90.00

In [47]:
#Exporta el DataFrame resultante a un archivo .csv separado por comas con el nombre "astronautas_calificados.csv".
astro2.to_csv("astronautas_calificados.csv")